#!/bin/bash

# Source icon file (generated by the agent)
SOURCE_ICON="/Users/ztlab130/code apps/TaskManagerApp/app-icon-new.png"

# Destination directories
RES_DIR="android/app/src/main/res"

# Define sizes for each density
# mipmap-mdpi: 48x48
# mipmap-hdpi: 72x72
# mipmap-xhdpi: 96x96
# mipmap-xxhdpi: 144x144
# mipmap-xxxhdpi: 192x192

# Ensure source exists
if [ ! -f "$SOURCE_ICON" ]; then
    echo "Error: Source icon not found at $SOURCE_ICON"
    exit 1
fi

echo "Updating Android icons..."

# Function to resize and copy
update_icon() {
    local folder=$1
    local size=$2
    local dest="$RES_DIR/$folder/ic_launcher.png"
    local dest_round="$RES_DIR/$folder/ic_launcher_round.png"

    echo "Resizing to $size x $size for $folder..."
    
    # Create directory if it doesn't exist (though it should)
    mkdir -p "$RES_DIR/$folder"

    # Resize for square icon and FORCE PNG format
    sips -s format png -z $size $size "$SOURCE_ICON" --out "$dest" > /dev/null
    
    # Reuse the same icon for round for now (in a real scenario we might want a circular mask, 
    # but the generated icon is already a rounded square-ish shape, usually Android wraps it. 
    # To be safe and avoid build errors if round icon is expected, we copy it there too).
    # Ideally, we should mask it. For this MVP, we copy the same file.
    cp "$dest" "$dest_round"
}

update_icon "mipmap-mdpi" 48
update_icon "mipmap-hdpi" 72
update_icon "mipmap-xhdpi" 96
update_icon "mipmap-xxhdpi" 144
update_icon "mipmap-xxxhdpi" 192

echo "Android icons updated successfully!"
